---
title: "Capacidade institucional no enfrentamento à violência de gênero"
author: "Bruna Gomes Guimarães"
date: "today"
number-sections: true

format:
  revealjs:
    self-contained: true 
    embed-resources: true
    theme: simple
    css: style.css
    slide-number: true
    smaller: true
    center: true
    fig-align: center
    fig-width: 8
    fig-height: 6
editor: visual
---

A pesquisa

Este projeto de pesquisa se propõe a investigar a expansão, a estagnação ou a retração de instituições pró-mulheres e seus efeitos no enfrentamento à violência de gênero, por isso busca responder a seguinte questão de pesquisa:

Qual é o efeito da capacidade institucional pró-mulheres sobre as taxas de violência de gênero?

Motivação empírica

• A violência contra mulheres mantém dinâmica persistente no Brasil.

• Embora os homicídios gerais apresentem tendência de queda, entre as mulheres essa redução ocorre de forma mais lenta e menos expressiva.

• Esse padrão sugere que a violência de gênero possui dinâmica própria e não responde necessariamente da mesma forma às políticas gerais de segurança pública.

• Paralelamente, as últimas décadas foram marcadas pela expansão de instituições e políticas pró-mulheres nos municípios brasileiros.

• Dados da MUNIC/IBGE mostram crescimento de organismos executivos, conselhos, planos e serviços especializados voltados às mulheres, embora distribuídos de forma desigual no território.

A pesquisa pode permitir uma melhor análise de quão heterogenea foi, e é, essa expansão institucional e pretende contribuir em uma discussão sobre a compreensão dos efeitos da expansão institucional.

Motivação teórica

Parte-se da ideia de que as instituições pró-mulheres são elementos fundamentais para o enfrentamento à violência de gênero, pois constituem estruturas que moldam comportamentos, rotinas e capacidades de resposta estatal frente a esse problema público, influenciando, por sua vez, as decisões individuais.

Essas estruturas formais possuem escopo e finalidades diversos. Na maior parte das vezes, personificam-se nos serviços especializados previstos na LMP ou em leis estaduais, tais como: delegacias especializadas, centros de atendimento, juizados, promotorias de justiça, casas de acolhimento e centros de saúde, além de políticas públicas e programas específicos.

A diversidade institucional quanto à natureza dessas estruturas justifica um olhar aprofundado sobre a tendência da capacidade estatal.

Literatura base

Institucionalismo histórico — Hall (1991), DiMaggio e Powell (1991), Steinmo, Thelen e Longstreth (1992):

Definição de instituições, persistência estrutural, legitimidade e impactos sociais e políticos das estruturas estatais.

Capacidades estatais e institucionalização de políticas públicas — Gomide e Pires (2014):

Análise sobre a capacidade do Estado de implementar políticas públicas em contextos democráticos, ambientes e arranjos institucionais.

Instituições pró-mulheres, Women’s Policy Agencies e State Feminism — Franceschet (2010), Gomes e Avellaneda (2021) e Gomes et al. (2025):

Conceituação das instituições pró-mulheres em perspectiva mundial e discussão sobre seus efeitos sociais.

Estudos sobre subnotificação e registros de violência de gênero (realização de revisão sistemática da literatura)

Indicadores sociais (Jannuzzi, 2005):

Ferramentas para a investigação acadêmica sobre mudanças e determinantes dos fenômenos sociais.

{r, include = FALSE}
#| include: false
pacman::p_load(readxl, knitr, dplyr, tidyr, ggplot2, ggstatsplot, scales, kableExtra, stringr)

{r}
#| echo: false
#| column: screen
#| out-width: 100%

matriz_estudos_ajustada <- read.csv("matriz_estudos_ajustada.csv")

ggplot(
  matriz_estudos_ajustada,
  aes(
    x = tipo_intervencao,
    y = resultado,
    fill = n 
  )
) +
  
  geom_tile(
    color = "white",
    linewidth = 1.5
  ) +
  
  geom_text(
    aes(label = estudos_no_bloco),
    size = 2.5,            
    fontface = "bold",
    color = "black",
    lineheight = 0.85     
  ) +
  
  scale_fill_gradient(
    low = "#f7fbff",
    high = "#2171b5"
  ) +
  
  scale_x_discrete(position = "top") +
  
  labs(
    title = "Síntese dos achados da revisão sistemática",
    subtitle = "Distribuição dos estudos segundo tipo de intervenção e resultado observado",
    x = "Tipo de intervenção institucional",
    y = "Resultado observado",
    fill = "Número\nde estudos"
  ) +
  
  theme_minimal(base_size = 10) +
  
  theme(
    plot.title = element_text(
      face = "bold",
      size = 15,
      margin = margin(b = 10)
    ),
    
    plot.subtitle = element_text(
      size = 10,
      margin = margin(b = 20)
    ),
    
    axis.title = element_text(
      face = "bold"
    ),
    
    panel.grid = element_blank(),
    
    # Alinhamento do texto do eixo X na parte de cima
    axis.text.x = element_text(
      angle = 0,             # Ângulo 0 no topo fica mais retilíneo e limpo para ler
      hjust = 0.5,
      vjust = 0.5
    ),
    
    legend.position = "right"
  )

Hipóteses

H1a: quanto maior a capacidade institucional pró-mulheres, maior a tendência de aumento da violência registrada, associada à redução da subnotificação.

H1b: no longo prazo, maiores níveis de capacidade institucional tendem a estar associados à redução da incidência da violência de gênero.

H2: instituições de segurança pública e justiça tendem a produzir efeitos mais significativos do que estruturas de outras naturezas.

Objetivos

Geral: construir um índice sintético temporal de capacidade institucional pró-mulheres e investigar seus efeitos sobre taxas de violência de gênero.

Identificar instituições pró-mulheres implantadas desde 2007;

Construir um índice sintético temporal de capacidade institucional;

Examinar a expansão desigual entre áreas institucionais;

Consolidar indicadores de violência letal e não letal;

Estimar o efeito do índice sobre os indicadores de violência.

Metodologia

Tipo de pesquisa

Quantitativa

Observacional

Longitudinal

Dados em painel município-ano

Variável independente

Índice de capacidade institucional pró-mulheres

Construído a partir de variáveis binárias de presença/ausência ou cobertura institucional[^Grande parte do arcabouço institucional da Lei Maria da Penha é operacionalizado pelos estados; Muitas instituições possuem localização física em um município, mas cobertura regional sobre vários territórios.]

Variável dependente

Violência não letal registrada

Violência doméstica estupro importunação sexual outros registros disponíveis

Violência letal

Homicídios de mulheres

Feminicídios [^Dados abertos a partir de 2018]

Os indicadores de violência serão normalizados por taxas populacionais, buscando garantir comparabilidade entre municípios com diferentes tamanhos demográficos.

Pensar em uma normalização por população feminina.

Casos

Minas Gerais: 853 municípios

São Paulo: 645 municípios

Período: 2007 a 2024

Coleta

Dados secundários: MUNIC, Fundação João Pinheiro, DATASUS, SSPs.

Dados primários: solicitações via Lei de Acesso à Informação.

Estruturação em banco longitudinal.

Exemplo da estrutura do banco com um município

{r}
#| echo: false
library(DT)
dados <- read_xlsx("df_bh.xlsx")

datatable(dados, filter = "top")

{r}
#| echo: false
#| column: screen
#| out-width: 100%

dados_long <- dados %>%
  select(ano, cmdm, cerna, sima, creas, trajeto_moda, deam, tjmg, mpmg, dpmg, pavmg) %>%
  pivot_longer(
    cols = -ano,
    names_to = "instituicao",
    values_to = "presenca"
  )

ggplot(dados_long, aes(x = ano, y = instituicao, fill = factor(presenca))) +
  geom_tile(color = "white") +
  scale_fill_manual(
    values = c("0" = "grey90", "1" = "steelblue"),
    labels = c("Ausente", "Presente"),
    name = ""
  ) +
  theme_minimal() +
  labs(
    title = "Exemplo da evolução da capacidade institucional",
    subtitle = "Exemplo com dados exploratórios",
    caption = "Fonte: Guimarães, Bruna (2026)/Dados de um município",
    x = "Ano",
    y = "Instituição"
  )

Legenda

trajeto_moda: programa da Subsecretaria de Inclusão Produtiva, Trabalho, Emprego e Renda com o objetivo de promover a inclusão produtiva e geração de renda de mulheres em situação de vulnerabilidade.

sima : Sistema Integrado de Monitoramento e Avaliação em Direitos Humanos – SIMA Mulher – 2020 - atendimento e acompanhamento online

tjmg – Juizados Especiais de Violência Doméstica e Familiar contra a Mulher

pavmp – Programas de Atenção à Violência (PAVs)

mpmg – Promotorias Especializadas

dpmg - Núcleos da Mulher nas Defensorias Públicas

deam - Delegacias Especializadas de Atendimento à Mulher

creas - Centros de Referência Especializado de Assistência Social

cmdm – Conselho Municipal dos Direitos das Mulheres

cerna: Centro Risoleta Neves de atendimento às mulheres

{r}
#| echo: false
#| column: screen
#| out-width: 80%

df_plot <- read.csv("df_plot.csv")

df_plot %>%
  ggplot(aes(x = ano, y = valor_normalizado, group = indicador, color = indicador)) +
  
  geom_line(linewidth = 0.8, alpha = 0.9) +
  
  scale_color_manual(
    values = c(
      "capacidade institucional" = "#2171b5",         
      "taxa de homicídios de mulheres" = "red",        
      "taxa de violencia não letal" = "orange"        
    )
  ) +
  
  scale_x_continuous(breaks = seq(2007, 2024, by = 2)) +
  
  theme_bw(base_size = 12) +
  
  labs(
    x = "Ano",
    y = "Escala padronizada",
    title = " Exemplo exploratório com taxas de violência de gênero",
    subtitle = "Evolução da Capacidade Institucional e da violência de gênero",
    caption = "Fonte: Guimarães, Bruna (2026)/Dados e métricas simulados e normalizados de um município",
    color = "Indicadores analisados"
  ) +
  
  theme(
    plot.title = element_text(face = "bold", size = 18, margin = margin(b = 6)),
    plot.subtitle = element_text(size = 10, color = "#4b4b4b", margin = margin(b = 13)),
    axis.title = element_text(face = "bold", size = 12),
    legend.position = "bottom", 
    legend.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

Técnicas de análise

Construção do índice:

Análise de Componentes Principais — PCA

Possível uso de Análise de Correspondência ou Teoria de Resposta ao Item, caso a natureza categórica dos dados recomende

Modelos econométricos para identificar efeito/impacto:

Painel com efeitos fixos municipais e temporais

Efeitos aleatórios para comparação

Modelos com defasagens temporais

Poisson ou binomial negativa se a variável dependente for contagem

Modelo para violência não letal

$$
Y_{it}^{NL} =
\beta_0 +
\beta_1 IC_{it} +
\beta_2 X_{it} +
\mu_i +
\lambda_t +
\varepsilon_{it}
$$

Se espera que maior uma capacidade institucional pode elevar registros oficiais em razão da redução da subnotificação.

Modelo para violência letal

$$
Y_{it}^{L} =
\beta_0 +
\beta_1 IC_{i,t-k} +
\beta_2 X_{it} +
\mu_i +
\lambda_t +
\varepsilon_{it}
$$

No médio e longo prazo, maior capacidade institucional pode reduzir a incidência da violência letal.

Legenda

$$
\begin{align*}
Y_{it}^{NL} &= \text{Violência não letal no município i no ano t} \\
Y_{it}^{L} &= \text{Violência letal no município i no ano t} \\
IC_{it} &= \text{Índice de capacidade institucional} \\
X_{it} &= \text{Variáveis de controle} \\
\mu_i &= \text{Efeitos fixos municipais} \\
\lambda_t &= \text{Efeitos temporais} \\
\varepsilon_{it} &= \text{Termo de erro} \\
k &= \text{Defasagem temporal}
\end{align*}
$$

Limitações

Capacidade institucional medida em presença/ausência deixa de fora informações sobre funcionamento e qualidade;

Recorte da seleção de casos impacta na generalização;

As diferenças entre os estados analisados na divulgação da violência não letal: isso afeta comparabilidade, longitudinalidade e padronização;

Endogeneidade: capacidade institucional e violência podem se influenciar mutuamente -> efeitos fixos municipais permite controlar características não observadas e constantes
no tempo que podem estar correlacionadas tanto com a capacidade institucional quanto com os indicadores de violência; 

Contribuições

Construção de índice sintético temporal.

Sistematização de dados municipais em formato longitudinal.

Diferenciação dos impactos entre violência letal e não letal.

Discussão sobre a redução da subnotificação como mecanismo institucional.

Contribuição para avaliação de políticas públicas de enfrentamento à violência de gênero.

Obrigada!

